### PR TITLE
Ported most maps to 0.7

### PR DESCRIPTION
**Pull request by Dune-jr**
@axblk map_update.exe unfortunately crashes on a few maps such as `break_of_day_v3.map` and  `ctf_auroch.map`

### CODE REVIEW

**Comment by axblk** [comment]
https://github.com/axblk/teeworlds/commit/97f1a082bc801d0b2515cd3d1d9310342e9413b8 fixes the issue.

**Comment by Dune-jr** [comment]
Thanks, @axblk, I'll update the PR then

**Comment by Sonix-** [comment]
Thank you a lot for converting them! Perhaps I dont think we should keep old versions in here too

**Comment by Sonix-** [comment]
@Dune-jr Just tested the maps, and all the converted maps have some sort of black outlines around the tiles :/
screenshot_2019-01-02_10-52-42
screenshot_2019-01-02_10-57-13
screenshot_2019-01-02_10-54-22

**Comment by Dune-jr** [comment]
Make them use external mapres, and it should be fine?

You can delete the old maps btw

**Comment by Sonix-** [comment]
They do use external mapres, already.
Except ctf_guano so far.

**Comment by Dune-jr** [comment]
Strange. When I remap them they look fine:

image

Maybe @axblk has a clue

**Comment by axblk** [comment]
@dune-jr did the tool have access to the data directory? Right now it analyzes the mapres files to set some flags.
I could precalculate these values so you can use the tool without any external data.

**Comment by Dune-jr** [comment]
Probably the issue, @axblk. Thanks, I'll fix it myself with a proper data dir

**Pull request merged**
